name: presensi_pintar_ta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  camera: ^0.10.3+2
  image: ^3.0.2
  tflite_flutter: ^0.9.0
  google_mlkit_face_detection: ^0.5.0
  path_provider: ^2.0.14
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  reactive_forms: ^15.0.0
  fluttertoast: ^8.2.1
  geolocator: 9.0.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  dio: ^5.1.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.10
  intl: ^0.18.1
  shimmer: ^2.0.0
  reactive_file_picker: ^1.0.0
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/mobilefacenet.tflite
    - assets/
